### ISSUE TITLE
Twice the compile time compared to cmdstan

### ISSUE THREAD

**Issue by aseyboldt** [roualdes/bridgestan#151]
If I compile models using cmdstan, it seems to consistently finish about twice as fast as if I compile a model with bridgestan:

```stan
// justatest.stan
parameters {
    real x;
}
model {
    x ~ normal(0, 1);
}
```

Then 
```
%%time
compiled = bridgestan.compile_model("justatest.stan")
# Wall time: 15.1 s

%%time
model = cmdstanpy.CmdStanModel("foo", "justatest.stan")
# Wall time: 7.18 s
```

I would have expected pretty much no difference, or even a bit faster comiles for bridgestan, because it doesn't have to also compile the sampler and the command line tool?

**Comment by bob-carpenter** [comment]
To test compilation time, I'd put copies of the model in different places to make sure CmdStan isn't just reusing the BridgeStan compiled model.   Or try to clean out the compiled versions in between.  But if that's the difference, I'd expect CmdStanModel to be a split second.

In CmdStan, we only have to translate the Stan program to a C++ class.  The sampler and command-line tools are compiled in separate translation units and then linked.  The linking does need to happen, though, so that takes a bit of time.

Do you know if BridgeStan and CmdStanPy compile at the same optimization level?  I hope CmdStanPy isn't default to `O = 0`, as that would be very slow.  @mitzimorris should know.

**Comment by WardBrian** [comment]
I wonder if it’s slower to compile position independent code? It’s also possible some of the precompiled header logic in CmdStan didn’t make it into our makefile, though that stuff is very brittle in my experience

**Comment by aseyboldt** [comment]
I don't think the difference is due to caching, just to make sure I gave it slightly different models, and that didn't change the timings. I'm also seeing the pretty consistently in by benchmarks with posteriordb.

> In CmdStan, we only have to translate the Stan program to a C++ class. The sampler and command-line tools are compiled in separate translation units and then linked. The linking does need to happen, though, so that takes a bit of time.

Ah, that does make sense. Still doesn't explain the difference I think though...

> Do you know if BridgeStan and CmdStanPy compile at the same optimization level? I hope CmdStanPy isn't default to O = 0, as that would be very slow. @mitzimorris should know.

I don't see a big difference in time for a gradient evaluation between bridgestan and cmdstan, so I don't think that's it either. A small difference might be lost in all the other things that differ, but I'm pretty sure something like `O0` would be very noticeable.

I guess it could also be because we also compile the hessian? Or something in a makefile isn't right and it recompiles something it shouldn't...

**Comment by bob-carpenter** [comment]
Hessians will add overhead.  But it shouldn't be that much because the Hessian code itself is fast and there's nothing else to compile in forward mode other than the functions being used in the code.   But then that's also true for the reverse mode functions, so maybe it is just the Hessians.  The only way I know how to test that would be modifying the code, but if it really is just the Hessians slowing things down, then we probably want to be able to conditionally compile w/o Hessians.

**Comment by WardBrian** [comment]
If you compile with autodiff hessians you’re also including all of stan/math/fwd, which definitely adds a lot of files for the preprocessor to handle

**Comment by mitzimorris** [comment]
CmdStanPy doesn't change the default optimization level - it just runs the makefile.

**Comment by aseyboldt** [comment]
Seems the hessian code is behind a compile time flag right now, and that was off in the code above. To make sure I just deleted all references to the hessian in `model_rng.cpp` in the `.bridgestan/.../src/` dir, and that didn't change the compile (after compiling one model once, the first time compiling any model was ~40s). Assuming I didn't miss anything, I think that should exclude the hessian as an explanation.

**Comment by WardBrian** [comment]
I can take a closer look tomorrow, with that ruled out my questions would be:
Are there any additional commands used in our compilation compared to CmdStan (I think not, but good to check)
Which commands invoked by make specifically are slower, assuming it isn’t just “all of them”

**Comment by aseyboldt** [comment]
I was just running into missing symbol issues with models involving sundials, and that made be check the variables in the makefile. Things there don't seem right to me, and that might be the source of this issue as well. It looks like some setup code never ended up being executed. For instance the sundials libs aren't precompiled (no sundials shared libs anywhere in the `~.bridgestan` directory), and the linker flags for those are empty. I think the `ode` example in the test modules doesn't seem to cover sundials either, as that is just using a runge kutta solver. 

The output of `make` in the `.bridgestan/bridgestan*/` dir is for me:

```
  Current configuration:
  - OS (Operating System):       Linux
  - CXX (Compiler):              g++
  - CXX_TYPE                     gcc
  - Compiler version:            12.3
  - O (Optimization Level):      3
  Library configuration:
  - EIGEN                        ./stan/lib/stan_math/lib/eigen_3.4.0
  - BOOST                        ./stan/lib/stan_math/lib/boost_1.78.0
  - SUNDIALS                     ./stan/lib/stan_math/lib/sundials_6.1.1
  - TBB                          ./stan/lib/stan_math/lib/tbb_2020.3
  - GTEST                        ./stan/lib/stan_math/lib/benchmark_1.5.1/googletest/googletest
  - STAN_THREADS                
  - STAN_OPENCL                 
  - STAN_MPI                    
  Compiler flags (each can be overriden separately):
  - CXXFLAGS_LANG                -std=c++1y
  - CXXFLAGS_WARNINGS            -Wno-sign-compare -Wno-ignored-attributes
  - CXXFLAGS_OPTIM              
  - CXXFLAGS_FLTO               
  - CXXFLAGS_BOOST              
  - CXXFLAGS_EIGEN              
  - CXXFLAGS_OS                  -pthread -D_REENTRANT
  - CXXFLAGS_GTEST              
  - CXXFLAGS_THREADS            
  - CXXFLAGS_OPENCL             
  - CXXFLAGS_TBB                 -I ./stan/lib/stan_math/lib/tbb_2020.3/include
  - CXXFLAGS_OPTIM_TBB          
  - CXXFLAGS_MPI                
  - CFLAGS_SUNDIALS             
  - CXXFLAGS_SUNDIALS            -pipe
  - CXXFLAGS_OPTIM_SUNDIALS     
  LDLIBS:
  - LDLIBS_LANG                 
  - LDLIBS_WARNINGS             
  - LDLIBS_EIGEN                
  - LDLIBS_BOOST                
  - LDLIBS_SUNDIALS             
  - LDLIBS_OS                   
  - LDLIBS_GTEST                
  - LDLIBS_OPENCL               
  - LDLIBS_TBB                   -Wl,-L,/home/adr/.bridgestan/bridgestan-2.1.1/stan/lib/stan_math/lib/tbb -Wl,-rpath,/home/adr/.bridgestan/bridgestan-2.1.1/stan/lib/stan_math/lib/tbb
  - LDLIBS_MPI                  
  LDFLAGS:
  - LDFLAGS_LANG                
  - LDFLAGS_WARNINGS            
  - LDFLAGS_EIGEN               
  - LDFLAGS_BOOST               
  - LDFLAGS_SUNDIALS            
  - LDFLAGS_OS                  
  - LDFLAGS_GTEST               
  - LDFLAGS_OPENCL              
  - LDFLAGS_TBB                  -Wl,-L,/home/adr/.bridgestan/bridgestan-2.1.1/stan/lib/stan_math/lib/tbb -Wl,-rpath,/home/adr/.bridgestan/bridgestan-2.1.1/stan/lib/stan_math/lib/tbb
  - LDFLAGS_MPI                 
```
